Reorder docker-push script

diff --git a/docker-push b/docker-push
--- a/docker-push
+++ b/docker-push
@@ -4,23 +4,23 @@ set -e
 
 cd $(dirname $0)
 
+if [[ -n $(git status -s) ]]; then
+	echo "ERROR: There are uncommitted changes"
+	exit 1
+fi
+
 if [ $(docker-machine status default) != "Running" ]; then
 	docker-machine start default
 fi
 
 eval $(docker-machine env default)
 
-if [[ -n $(git status -s) ]]; then
-	echo "ERROR: There are uncommitted changes"
-	exit 1
-fi
+# Get the current Git commit hash
+COMMIT_HASH=$(git rev-parse --short HEAD)
 
 # Bundle application
 DOCKER_REGISTRY=296296715593.dkr.ecr.us-east-1.amazonaws.com
 DOCKER_REGISTRY=$DOCKER_REGISTRY ./docker-bundle
-
-# Get the current Git commit hash
-COMMIT_HASH=$(git rev-parse --short HEAD)
 
 # Tag and upload local docker images
 docker tag -f filecanvas/app:$COMMIT_HASH $DOCKER_REGISTRY/filecanvas/app:$COMMIT_HASH
